### ISSUE TITLE
Calico IP range should be a config option

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/layer-calico#4]
We're using a hardcoded 192.168.0.0/16 range right now. It needs to be a config option.

From #1:
> Config would be better extended to specify the IP range (default is 192.168.0.0/16).  To change this, configure_calico_pool() should delete the existing pool and create a new one with the IPIP/nat-outgoing options.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809355.
