### ISSUE TITLE
Need to update calico-node service when private IP changes

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/layer-calico#5]
From #1, the private IP used in [install_calico_service()](https://github.com/juju-solutions/layer-calico/pull/1/files#diff-86341d98ab0913b74cf19a4edab8e404R94) can change, so we need to re-render the service file with the correct IP if that occurs.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809356.
